server:
  port: 8081
spring:
  application:
    name: oss-spring-boot-starter
  oss:
    type: qiniu
    qiniu:
      bucket: hello-bucket
      access-key: RUGeyFR65qupjryY_hQdPJ9Ktb8QlH-vIPfv2Vx6
      secret-key: oVPImUQYHOZAAF-6MpBjtWNq0i6zNPqw481j7xvt
    aliyun:
      bucket: null
      endpoint: null
      access-key: null
      secret-key: null
    tencent:
      bucket: null
      access-key: null
      secret-key: null
    
eureka:
  client:
    service-url:
      defaultZone: http://59.110.61.44:8761/eureka/

swagger:
  global-token: true
  group-name: oss
  title: OSS服务
  description: OSS服务程序
  name: linzl
  url: http://baidu.com
  email: 110@qq.com
