server:
  port: 8081
spring:
  application:
    name: spring-kafka
kafka:
  bootstrap-servers: 192.168.3.125:9092
  topic:
    basictopic: sleuth
    advancedtopic: advancedtopic
                   
logging:
  path: D:/log    